// utils/disposableEmails.ts
// Simple list and checker for disposable email domains (MVP)

const disposableDomains = [
  'mailinator.com',
  '10minutemail.com',
  'guerrillamail.com',
  'tempmail.com',
  'yopmail.com',
  'trashmail.com',
  'getnada.com',
  'fakeinbox.com',
  'sharklasers.com',
  'dispostable.com',
  'maildrop.cc',
  'mintemail.com',
  'throwawaymail.com',
  'moakt.com',
  'mytemp.email',
  'emailondeck.com',
  'spamgourmet.com',
  'mailnesia.com',
  'temp-mail.org',
  'tempail.com',
  'mailcatch.com',
  'spambog.com',
  'spambog.de',
  'spambog.ru',
  'spambog.xyz',
  'spambog.pl',
  'spambog.com.br',
  'spambog.cf',
  'spambog.ga',
  'spambog.gq',
  'spambog.ml',
  'spambog.tk',
  'mail-temp.com',
  'tempinbox.com',
  'tempm.com',
  'tempr.email',
  'maildrop.cc',
  'disposablemail.com',
  'disposablemail.net',
  'disposablemail.org',
  'disposableemailaddresses.com',
  'mailnesia.com',
  'mailnull.com',
  'meltmail.com',
  'nowmymail.com',
  'objectmail.com',
  'proxymail.eu',
  'rcpt.at',
  'trashmail.at',
  'trashmail.com',
  'trashmail.de',
  'trashmail.me',
  'trashmail.net',
  'trashmail.org',
  'trashmail.ws',
  'maildrop.cc',
  'maildrop.cf',
  'maildrop.ga',
  'maildrop.gq',
  'maildrop.ml',
  'maildrop.tk',
  'maildrop.cc',
  'maildrop.cf',
  'maildrop.ga',
  'maildrop.gq',
  'maildrop.ml',
  'maildrop.tk',
  // ...add more as needed
];

export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase();
  return !!domain && disposableDomains.includes(domain);
}
